version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: keter-db
    restart: always
    environment:
      POSTGRES_USER: rafael_admin
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: keter_db
    ports:
      - "5432:5432"
    volumes:
      - keter_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: keter-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Host=db;Database=keter_db;Username=rafael_admin;Password=your_secure_password"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: keter-ui
    ports:
     - "8080:3000"
    environment:
      - VITE_API_URL=http://127.0.0.1:5001
    volumes:
      - ./client:/app         
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true    
    tty: true

volumes:
  keter_db_data: