// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316094003_UpdateBoardTaskTagColumn")]
    partial class UpdateBoardTaskTagColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectTaskTag", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("ProjectTaskTag");
                });

            modelBuilder.Entity("server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "266b0ca5-bc8f-4801-8127-4e55a74b573a",
                            Email = "working@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "WORKING@KETER.RO",
                            NormalizedUserName = "WORKING_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEFP3jl+a2B90QeNITqNc+I6sKLY4AoZg8PU3Gh9YuNpJj7OZAYGuthIXHmGJaTWbeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18206443-e478-4391-bf9d-2d513265b3db",
                            TwoFactorEnabled = false,
                            UserName = "working_raccoon"
                        },
                        new
                        {
                            Id = "user-member-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c6083cf-c99c-47da-8555-9ce339b841da",
                            Email = "money@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MONEY@KETER.RO",
                            NormalizedUserName = "MONEY_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAENmGd4zFirIqAt575N2ye24miisf/lCl2JWf6TT0wT8QOU5Iu7epRbQwJ1IGxLGxRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4ae1db07-a152-47f6-ac48-ca4a8d3dfbef",
                            TwoFactorEnabled = false,
                            UserName = "money_raccoon"
                        },
                        new
                        {
                            Id = "user-member-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4febbe3-683c-49f6-a3da-de0590fa4b54",
                            Email = "cool@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "COOL@KETER.RO",
                            NormalizedUserName = "COOL_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEEUgDxTmY6nR87aA7gOTi/cKcqq1oWUf67ymF16ZXYCuJTAHU8PIvrhgA1PXW3f3Qw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2e7a44ce-aaa6-482d-9c0a-68249e925a43",
                            TwoFactorEnabled = false,
                            UserName = "cool_raccoon"
                        },
                        new
                        {
                            Id = "user-member-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "daa76403-1231-4e0e-8a52-7cbf7f531ab8",
                            Email = "bath@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BATH@KETER.RO",
                            NormalizedUserName = "BATH_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEKr1dInUQW9kuFgybcG+Wtb4Bs/KAP1a2I921atX3mi2KeC2Nnv4Jj/pq5mHz6bL/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7aadf32c-27bb-4f09-b677-66ab763bc6bf",
                            TwoFactorEnabled = false,
                            UserName = "bath_raccoon"
                        },
                        new
                        {
                            Id = "user-member-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6299ce2a-aa22-495b-b2ad-a5021f4e157d",
                            Email = "banana@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BANANA@KETER.RO",
                            NormalizedUserName = "BANANA_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEFC7/OySRM4eF3ran984lRjHhzKAqmwa9u2YQJfbJ3r9tApqyPBc4tqSoiaDVkU/Fg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75d17af1-6b78-405a-b509-0adca77103c1",
                            TwoFactorEnabled = false,
                            UserName = "banana_raccoon"
                        });
                });

            modelBuilder.Entity("server.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Name = "Backend C#",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Frontend React",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("server.Models.BoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardColumns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444411"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444412"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444413"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Order = 2,
                            Title = "Done"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444421"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444422"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444423"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Order = 2,
                            Title = "Done"
                        });
                });

            modelBuilder.Entity("server.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 16, 9, 40, 3, 414, DateTimeKind.Utc).AddTicks(1290),
                            Description = "Proiect pentru facultate",
                            Name = "Platforma Keter",
                            OwnerId = "user-admin-1"
                        });
                });

            modelBuilder.Entity("server.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ColumnId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            AssignedUserId = "user-member-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444413"),
                            Order = 0,
                            Title = "Configurare Docker"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            AssignedUserId = "user-member-2",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444412"),
                            Order = 0,
                            Title = "Creare DbContext"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AssignedUserId = "user-member-3",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444421"),
                            Order = 0,
                            Title = "Design UI in SCSS"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            AssignedUserId = "user-member-4",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444421"),
                            Order = 1,
                            Title = "Integrare Axios"
                        });
                });

            modelBuilder.Entity("server.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            ColorHex = "#3b82f6",
                            Name = "Feature"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            ColorHex = "#ef4444",
                            Name = "Bug"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            ColorHex = "#10b981",
                            Name = "DevOps"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTaskTag", b =>
                {
                    b.HasOne("server.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.Board", b =>
                {
                    b.HasOne("server.Models.Project", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("server.Models.BoardColumn", b =>
                {
                    b.HasOne("server.Models.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("server.Models.Project", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("server.Models.ProjectTask", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("server.Models.BoardColumn", "Column")
                        .WithMany("Tasks")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Column");
                });

            modelBuilder.Entity("server.Models.ApplicationUser", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("OwnedProjects");
                });

            modelBuilder.Entity("server.Models.Board", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("server.Models.BoardColumn", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("server.Models.Project", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
