// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328175331_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-user-id",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "role-admin-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-1",
                            RoleId = "role-admin-id"
                        },
                        new
                        {
                            UserId = "user-member-1",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-member-2",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-member-3",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-member-4",
                            RoleId = "role-user-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectMembers", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = "user-member-1"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = "user-member-2"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = "user-member-3"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = "user-member-4"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112"),
                            UserId = "user-member-1"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112"),
                            UserId = "user-member-3"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113"),
                            UserId = "user-member-2"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113"),
                            UserId = "user-member-4"
                        },
                        new
                        {
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111114"),
                            UserId = "user-member-1"
                        });
                });

            modelBuilder.Entity("ProjectTaskTag", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("ProjectTaskTag");

                    b.HasData(
                        new
                        {
                            TagsId = new Guid("55555555-5555-5555-5555-555555555501"),
                            TasksId = new Guid("33333333-3333-3333-3333-333333333301")
                        },
                        new
                        {
                            TagsId = new Guid("55555555-5555-5555-5555-555555555502"),
                            TasksId = new Guid("33333333-3333-3333-3333-333333333301")
                        },
                        new
                        {
                            TagsId = new Guid("55555555-5555-5555-5555-555555555501"),
                            TasksId = new Guid("33333333-3333-3333-3333-333333333304")
                        },
                        new
                        {
                            TagsId = new Guid("55555555-5555-5555-5555-555555555503"),
                            TasksId = new Guid("33333333-3333-3333-3333-333333333307")
                        },
                        new
                        {
                            TagsId = new Guid("55555555-5555-5555-5555-555555555519"),
                            TasksId = new Guid("33333333-3333-3333-3333-333333333315")
                        },
                        new
                        {
                            TagsId = new Guid("55555555-5555-5555-5555-555555555512"),
                            TasksId = new Guid("33333333-3333-3333-3333-333333333318")
                        },
                        new
                        {
                            TagsId = new Guid("55555555-5555-5555-5555-555555555515"),
                            TasksId = new Guid("33333333-3333-3333-3333-333333333318")
                        });
                });

            modelBuilder.Entity("server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8fa7cc5-0701-4c22-9d55-b23f0333459a",
                            Email = "working@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "WORKING@KETER.RO",
                            NormalizedUserName = "WORKING_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEFpnQVi/Qveb/rBOG29Ak+iopKy6PtqJulgQe5MF/gmJrWYdjH5WuvFlUzBJUn1yWw==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "/../avatars/WorkingRaccoon.png",
                            SecurityStamp = "93328776-7284-4cf0-b6e4-81df7add9606",
                            TwoFactorEnabled = false,
                            UserName = "working_raccoon"
                        },
                        new
                        {
                            Id = "user-member-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74f9f2d1-c2ef-4781-bd71-40044854418c",
                            Email = "money@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MONEY@KETER.RO",
                            NormalizedUserName = "MONEY_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAELu9mrdPne73eamn31VPMoyIlX3sQvKDUW8gJWg31mVqHDydWRsaUJWD9oq0lcN3qA==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "/../avatars/CardRaccoon.png",
                            SecurityStamp = "057d7c40-8839-4a76-b01f-70aed706e197",
                            TwoFactorEnabled = false,
                            UserName = "money_raccoon"
                        },
                        new
                        {
                            Id = "user-member-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fc0a66e1-705e-4f00-94b5-ae772706caad",
                            Email = "cool@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "COOL@KETER.RO",
                            NormalizedUserName = "COOL_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ/vDdlno5YFmO4GQsUkFSCVlm4SKvG8HXB/7niElywkuqjFrI5M+WfaDZvpPOryTQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "/../avatars/coolRaccoon.png",
                            SecurityStamp = "ca6b7980-4207-462c-9640-f401b7d40f52",
                            TwoFactorEnabled = false,
                            UserName = "cool_raccoon"
                        },
                        new
                        {
                            Id = "user-member-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da692d93-83f5-4b21-8971-f98761176a35",
                            Email = "bath@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BATH@KETER.RO",
                            NormalizedUserName = "BATH_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEPOnKazJ+kDZ7yzDRudiJEMVpSDhdf8frWGinggcPjLqReAIGvDc1JmSvm49EzUZDQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "/../avatars/BathRaccoon.png",
                            SecurityStamp = "d2fab3f3-b36c-4b3d-852b-8885d938ebb3",
                            TwoFactorEnabled = false,
                            UserName = "bath_raccoon"
                        },
                        new
                        {
                            Id = "user-member-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c30b329-a2ea-4993-b033-1ea2800c0c54",
                            Email = "banana@keter.ro",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BANANA@KETER.RO",
                            NormalizedUserName = "BANANA_RACCOON",
                            PasswordHash = "AQAAAAIAAYagAAAAEN+b4fywr7HW1F0qBwgheaEbwY0OBWanlAPGoP6pyxNFMTfzuVVq1G7vKnG7B3UIMg==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "/../avatars/BananaRaccoon.png",
                            SecurityStamp = "3dac9d85-5dfa-43c5-9136-01503a24421b",
                            TwoFactorEnabled = false,
                            UserName = "banana_raccoon"
                        });
                });

            modelBuilder.Entity("server.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Name = "Backend C#",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Frontend React",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Name = "Dezvoltare Magazin",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Name = "Marketing",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            Name = "iOS App",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            Name = "Android App",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222227"),
                            Name = "Implementare ERP",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111114")
                        });
                });

            modelBuilder.Entity("server.Models.BoardColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardColumns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444411"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444412"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444413"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Order = 2,
                            Title = "Done"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444414"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444415"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444416"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Order = 2,
                            Title = "Done"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444417"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222223"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444418"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222223"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444419"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222223"),
                            Order = 2,
                            Title = "Done"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444420"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222224"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444421"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222224"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444422"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222224"),
                            Order = 2,
                            Title = "Done"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444423"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222225"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444424"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222225"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444425"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222225"),
                            Order = 2,
                            Title = "Done"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444426"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222226"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444427"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222226"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444428"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222226"),
                            Order = 2,
                            Title = "Done"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444429"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222227"),
                            Order = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444430"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222227"),
                            Order = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444431"),
                            BoardId = new Guid("22222222-2222-2222-2222-222222222227"),
                            Order = 2,
                            Title = "Done"
                        });
                });

            modelBuilder.Entity("server.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 28, 17, 53, 30, 910, DateTimeKind.Utc).AddTicks(2430),
                            Description = "Proiect pentru facultate",
                            Name = "Platforma Keter",
                            OwnerId = "user-admin-1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 3, 28, 17, 53, 30, 910, DateTimeKind.Utc).AddTicks(2430),
                            Description = "E-commerce cu React și C#",
                            Name = "Magazin Online",
                            OwnerId = "user-admin-1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2026, 3, 28, 17, 53, 30, 910, DateTimeKind.Utc).AddTicks(2440),
                            Description = "Aplicație de fitness",
                            Name = "Aplicație Mobilă",
                            OwnerId = "user-admin-1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTime(2026, 3, 28, 17, 53, 30, 910, DateTimeKind.Utc).AddTicks(2440),
                            Description = "ERP pentru firmă locală",
                            Name = "Sistem Gestiune",
                            OwnerId = "user-admin-1"
                        });
                });

            modelBuilder.Entity("server.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ColumnId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            AssignedUserId = "user-member-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444411"),
                            Order = 0,
                            Status = "To Do",
                            Title = "Implementare JWT Token"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            AssignedUserId = "user-member-2",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444411"),
                            Order = 1,
                            Status = "To Do",
                            Title = "Creare endpoint Login"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            AssignedUserId = "user-admin-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444411"),
                            Order = 2,
                            Status = "To Do",
                            Title = "Securizare rute API"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            AssignedUserId = "user-member-3",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444412"),
                            Order = 0,
                            Status = "In Progress",
                            Title = "Creare DbContext"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            AssignedUserId = "user-member-4",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444412"),
                            Order = 1,
                            Status = "In Progress",
                            Title = "Migrari baza de date"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            AssignedUserId = "user-member-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444413"),
                            Order = 0,
                            Status = "Done",
                            Title = "Configurare Docker"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333307"),
                            AssignedUserId = "user-member-3",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444414"),
                            Order = 0,
                            Status = "To Do",
                            Title = "Design UI in SCSS"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333308"),
                            AssignedUserId = "user-member-4",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444414"),
                            Order = 1,
                            Status = "To Do",
                            Title = "Integrare Axios"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333309"),
                            AssignedUserId = "user-admin-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444415"),
                            Order = 0,
                            Status = "In Progress",
                            Title = "Componenta BoardCard"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333310"),
                            AssignedUserId = "user-member-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444415"),
                            Order = 1,
                            Status = "In Progress",
                            Title = "Meniu de navigare"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333311"),
                            AssignedUserId = "user-member-2",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444415"),
                            Order = 2,
                            Status = "In Progress",
                            Title = "Grafic statistic (CSS Grid)"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333312"),
                            AssignedUserId = "user-member-3",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444416"),
                            Order = 0,
                            Status = "Done",
                            Title = "Setup initial Vite"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333313"),
                            AssignedUserId = "user-member-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444417"),
                            Order = 0,
                            Status = "To Do",
                            Title = "Integrare Stripe pentru plati"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333314"),
                            AssignedUserId = "user-member-3",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444419"),
                            Order = 0,
                            Status = "Done",
                            Title = "Design Pagina de Produs"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333315"),
                            AssignedUserId = "user-member-4",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444420"),
                            Order = 0,
                            Status = "To Do",
                            Title = "Setup Campanie Facebook Ads"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333316"),
                            AssignedUserId = "user-member-2",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444421"),
                            Order = 0,
                            Status = "In Progress",
                            Title = "Design bannere promovare"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333317"),
                            AssignedUserId = "user-member-3",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444423"),
                            Order = 0,
                            Status = "To Do",
                            Title = "Integrare Apple Login"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333318"),
                            AssignedUserId = "user-admin-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444425"),
                            Order = 0,
                            Status = "Done",
                            Title = "Setup initial proiect Swift"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333319"),
                            AssignedUserId = "user-member-1",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444427"),
                            Order = 0,
                            Status = "In Progress",
                            Title = "Push notifications cu Firebase"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333320"),
                            AssignedUserId = "user-member-4",
                            ColumnId = new Guid("44444444-4444-4444-4444-444444444429"),
                            Order = 0,
                            Status = "To Do",
                            Title = "Dezvoltare Modul HR"
                        });
                });

            modelBuilder.Entity("server.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            ColorHex = "#E27893",
                            Name = "Important",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            ColorHex = "#734FCF",
                            Name = "Programming",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            ColorHex = "#EDCF8E",
                            Name = "UI/UX",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555504"),
                            ColorHex = "#C28CAE",
                            Name = "Social Media",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555505"),
                            ColorHex = "#D9D9D9",
                            Name = "Optional",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555506"),
                            ColorHex = "#E27893",
                            Name = "Important",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555507"),
                            ColorHex = "#734FCF",
                            Name = "Programming",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555508"),
                            ColorHex = "#EDCF8E",
                            Name = "UI/UX",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555509"),
                            ColorHex = "#C28CAE",
                            Name = "Social Media",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555510"),
                            ColorHex = "#D9D9D9",
                            Name = "Optional",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111112")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555511"),
                            ColorHex = "#E27893",
                            Name = "Important",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555512"),
                            ColorHex = "#734FCF",
                            Name = "Programming",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555513"),
                            ColorHex = "#EDCF8E",
                            Name = "UI/UX",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555514"),
                            ColorHex = "#C28CAE",
                            Name = "Social Media",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555515"),
                            ColorHex = "#D9D9D9",
                            Name = "Optional",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111113")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555516"),
                            ColorHex = "#E27893",
                            Name = "Important",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555517"),
                            ColorHex = "#734FCF",
                            Name = "Programming",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555518"),
                            ColorHex = "#EDCF8E",
                            Name = "UI/UX",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555519"),
                            ColorHex = "#C28CAE",
                            Name = "Social Media",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111114")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555520"),
                            ColorHex = "#D9D9D9",
                            Name = "Optional",
                            ProjectId = new Guid("11111111-1111-1111-1111-111111111114")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectMembers", b =>
                {
                    b.HasOne("server.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTaskTag", b =>
                {
                    b.HasOne("server.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.Board", b =>
                {
                    b.HasOne("server.Models.Project", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("server.Models.BoardColumn", b =>
                {
                    b.HasOne("server.Models.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("server.Models.Project", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("server.Models.ProjectTask", b =>
                {
                    b.HasOne("server.Models.ApplicationUser", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("server.Models.BoardColumn", "Column")
                        .WithMany("Tasks")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Column");
                });

            modelBuilder.Entity("server.Models.Tag", b =>
                {
                    b.HasOne("server.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("server.Models.ApplicationUser", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("OwnedProjects");
                });

            modelBuilder.Entity("server.Models.Board", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("server.Models.BoardColumn", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("server.Models.Project", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
